### ISSUE TITLE
Support request for encryption key rotation

### ISSUE THREAD

**Issue by btall** [C0D1UM/django-secured-fields#40]
Currently, [django-fernet-encrypted-fields](https://django-fernet-fields.readthedocs.io/) uses Django's `SECRET_KEY` or a unique key defined in `SALT_KEY` for encryption.

However, rotating encryption keys is an important security practice that doesn't seem to be supported by **django-secured-fields**.

So I wonder if there are any plans to implement a mechanism similar to **django-fernet-encrypted-fields** for managing multiple encryption keys: https://django-fernet-fields.readthedocs.io/en/latest/#keys

**Comment by earthpyy** [comment]
Hello, thank you for raising the issue. I believe we can address it. While I cannot provide you a timeline atm, I will ensure that it is implemented. Thanks!

**Comment by earthpyy** [comment]
Hi @btall,
Thanks for waiting! Just wanna let you know that this was finally implemented and released in [v0.4.4](https://github.com/C0D1UM/django-secured-fields/releases/tag/v0.4.4)!

**Comment by btall** [comment]
Hi @earthpyy, 
Thank you for the update! 
I am glad to hear that it has been implemented and released in [v0.4.4](https://github.com/C0D1UM/django-secured-fields/releases/tag/v0.4.4). 
Looking forward to checking it out!
