### ISSUE TITLE
EncryptedFileStorage save method assumes the file pointer of content is at 0

### ISSUE THREAD

**Issue by schraal** [C0D1UM/django-secured-fields#43]
The save method immediately starts reading the content but instead should:

- save the position of the file pointer
- set it to 0
- do its thing
- reset the file pointer to the original position (instead of forcing it to 0)

Forcing the file pointer to 0 is a possibly unwanted side-effect of this method.

**Comment by earthpyy** [comment]
Released in [v0.4.4](https://github.com/C0D1UM/django-secured-fields/releases/tag/v0.4.4)
